In [6]:
import numpy as np
import pandas as pd
from scipy import ndimage, misc

In [7]:
## 2) Crear un vector de ceros de tamaño 10

respuesta = [0] * 10
respuesta

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [8]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

respuesta = [0] * 10
respuesta[5] = 1
respuesta

[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

In [10]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

respuesta = np.arange(50)
print(respuesta)
respuesta = respuesta[::-1]
print('------')
print(respuesta)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
------
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8

respuesta = np.arange(9).reshape(3,3)
respuesta

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
## 6) Encontrar los indices que no sean cero en un arreglo
arreglo = [1,2,0,0,4,0]
respuesta = []
for elemento, i in enumerate(arreglo):
    if i != 0:
        respuesta.append(elemento)

print(respuesta)

[0, 1, 4]


In [15]:
## 7) Crear una matriz de identidad 3 x 3 
respuesta = np.eye(3)
respuesta

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

respuesta = np.random.randint(1,100,3*3*3).reshape(3,3,3)
respuesta

array([[[56, 93, 69],
        [85, 22, 87],
        [87, 89,  2]],

       [[80, 49, 39],
        [97, 30, 85],
        [70, 26, 13]],

       [[60, 41, 21],
        [34, 52, 95],
        [ 4, 25, 54]]])

In [22]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

respuesta = np.random.randint(1,100,10*10).reshape(10,10)
print(respuesta)
print('-----')
print('Max: {}'.format(respuesta.max()))
print('-----')
print('Min: {}'.format(respuesta.min()))

[[24 28 79 66 16 89 37 60  6 50]
 [41 61 78 74 15 44 26 20 51 44]
 [99 62 59 41 52 63  3 68  5 35]
 [46 40  1  7 89 57 85 65  3 77]
 [74 52 55  6 43 32  8 57 35 45]
 [57 30 21 72 67 90 15 57 88 49]
 [67 68 14 36 22  9 95 62  8 85]
 [88 83 90 18 68 32 74 85 90 97]
 [33 33 75 72 87 76 22 64 67 76]
 [18 35  8 79 17  8 44 56 40 94]]
-----
Max: 99
-----
Min: 1


In [128]:
## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

mapache = misc.face() # imagen del mapache
mapache = mapache.reshape(-1,3)
print('Cantidad de colores totales: {}'.format(len(mapache)))
print(mapache)
mapache = np.unique(mapache, axis=0)
print('------------')
print('Cantidad de colores totales unicos: {}'.format(len(mapache)))
print(mapache)

Cantidad de colores totales: 786432
[[121 112 131]
 [138 129 148]
 [153 144 165]
 ...
 [120 156  95]
 [119 155  93]
 [118 154  92]]
------------
Cantidad de colores totales unicos: 134105
[[  0   0   5]
 [  0   0   7]
 [  0   0   9]
 ...
 [255 248 255]
 [255 249 255]
 [255 252 255]]


In [115]:
## 11) ¿Como crear una serie de una lista, diccionario o arreglo?

mylist = list('abcedfghijklmnopqrstuvwxyz') # lista
serie = pd.Series(mylist)
print('LISTA')
print(serie)
print('-----')

myarr = np.arange(26) # arreglo
serie = pd.Series(myarr)
print('ARREGLO')
print(serie)
print('-----')

mydict = dict(zip(mylist, myarr)) # dict
serie = pd.Series(mydict)
print('DICT')
print(serie)


LISTA
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
-----
ARREGLO
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64
-----
DICT
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [40]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)  
# Transformar la serie en dataframe y hacer una columna indice
print(ser)
print('------')
df = pd.DataFrame(ser)
df.reset_index(level=0, inplace=True)
df.rename(columns={'index': 'letras',0:'numeros'}, inplace=True)
df


a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64
------


letras  numeros
0       a        0
1       b        1
2       c        2
3       e        3
4       d        4
5       f        5
6       g        6
7       h        7
8       i        8
9       j        9
10      k       10
11      l       11
12      m       12
13      n       13
14      o       14
15      p       15
16      q       16
17      r       17
18      s       18
19      t       19
20      u       20
21      v       21
22      w       22
23      x       23
24      y       24
25      z       25

In [44]:
## 13) ¿Como combinar varias series para hacer un DataFrame?

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
datos = {'ser1': ser1, 'ser2': ser2}
df = pd.DataFrame(datos)
df

ser1  ser2
0     a     0
1     b     1
2     c     2
3     e     3
4     d     4
5     f     5
6     g     6
7     h     7
8     i     8
9     j     9
10    k    10
11    l    11
12    m    12
13    n    13
14    o    14
15    p    15
16    q    16
17    r    17
18    s    18
19    t    19
20    u    20
21    v    21
22    w    22
23    x    23
24    y    24
25    z    25

In [116]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

estan = ser1.isin(ser2)
ser1 = ser1[~estan]
ser1.values

array([1, 2, 3])

In [118]:
## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

no_comunes = pd.concat([ser1,ser2]).drop_duplicates(keep=False)
no_comunes.values

array([1, 2, 3, 6, 7, 8])

In [129]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser)
ser = np.array(ser.values)
valor_a_repetir = 'f'
veces = np.count_nonzero(ser == valor_a_repetir ) 
print('Cantidad de repeticiones de {}: {} '.format(valor_a_repetir, veces))

0     h
1     g
2     e
3     b
4     d
5     e
6     f
7     d
8     e
9     e
10    a
11    g
12    d
13    d
14    b
15    d
16    b
17    h
18    h
19    f
20    f
21    e
22    g
23    d
24    b
25    b
26    c
27    e
28    b
29    f
dtype: object
Cantidad de repeticiones de f: 4 


In [133]:
## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print('Serie original')
print(ser)
veces = ser.value_counts()
print('valores más repetidos, sus columnas son: (valor, cantidad repeticiones)')
print(veces)
no_mayores = [veces.index[2:]]
print('valores que no son los dos más repetitivos:')
print(list(no_mayores[0]))
print('ya cambiados a 0s:')
ser = ser.replace(list(no_mayores[0]), 0)
print(ser)

Serie original
0     4
1     3
2     2
3     3
4     2
5     2
6     3
7     1
8     3
9     1
10    2
11    1
dtype: int64
valores más repetidos, sus columnas son: (valor, cantidad repeticiones)
3    4
2    4
1    3
4    1
dtype: int64
valores que no son los dos más repetitivos:
[1, 4]
ya cambiados a 0s:
0     0
1     3
2     2
3     3
4     2
5     2
6     3
7     0
8     3
9     0
10    2
11    0
dtype: int64


In [64]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7,5))
df

0  1  2  3  4
0  3  6  1  5  8
1  2  5  4  6  1
2  8  8  2  2  9
3  1  6  5  1  7
4  9  7  8  2  5
5  9  4  2  7  3
6  9  8  7  8  4

In [67]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
resultado = ser.iloc[pos]
resultado

0     a
4     e
8     i
14    o
20    u
dtype: object

In [99]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
frame = pd.concat([ser1,ser2],axis=1) # axis =1 horizontal, = 0 vertical

resultado = pd.DataFrame(frame)
resultado

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [138]:
## 21)¿Obtener la media de una serie agrupada por otra serie?

#`groupby` tambien esta disponible en series.

frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
print('-----------------')
data = pd.Series(pesos.values, index=frutas)
data = data.groupby(by=frutas.values).median()
data

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['zanahoria', 'zanahoria', 'manzana', 'zanahoria', 'manzana', 'zanahoria', 'manzana', 'banana', 'zanahoria', 'banana']
-----------------


banana       9.0
manzana      5.0
zanahoria    4.0
dtype: float64

In [141]:
## 22)¿Como importar solo columnas especificas de un archivo csv?

path = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'

columnas = ["crim","zn","b","lstat"]
respuesta = pd.read_csv(path,nrows=10,usecols=columnas)
respuesta

crim    zn       b  lstat
0  0.00632  18.0  396.90   4.98
1  0.02731   0.0  396.90   9.14
2  0.02729   0.0  392.83   4.03
3  0.03237   0.0  394.63   2.94
4  0.06905   0.0  396.90   5.33
5  0.02985   0.0  394.12   5.21
6  0.08829  12.5  395.60  12.43
7  0.14455  12.5  396.90  19.15
8  0.21124  12.5  386.63  29.93
9  0.17004  12.5  386.71  17.10