In [1]:
import numpy as np

In [2]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [3]:
np.zeros(5) # para un arreglo solo se manda un numero 

# Para una matriz se manda una tupla o lista
np.zeros([5,5])
np.zeros((5,5)) 
np.zeros([100,300]) # siempre el último será el parámetros de las columnas y el penúltimo de las filas
np.ones([100,300])

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
# Crea una matriz de igual dimensiones con su diagonal = 1
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### NP.ARANGE

In [6]:
# Establece un inicio y un fin abierto para llenar un array

np.arange(5,20) # [5, 20[

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(12,-3)  # esto no vale

array([], dtype=int64)

In [8]:
np.arange(5,20,3)  # Del 5 al 20 abierto saltando de 3 en 3

array([ 5,  8, 11, 14, 17])

In [9]:
np.arange(-25,-20,0.7) 

array([-25. , -24.3, -23.6, -22.9, -22.2, -21.5, -20.8, -20.1])

In [10]:
np.arange(25,20,-0.4)

array([25. , 24.6, 24.2, 23.8, 23.4, 23. , 22.6, 22.2, 21.8, 21.4, 21. ,
       20.6, 20.2])

### .RESHAPE

In [15]:
np.arange(20).reshape(5,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [16]:
np.arange(20).reshape(5,2,2).reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.arange(20).reshape(5,2,2).shape

(5, 2, 2)

### OPERACIONES

In [18]:
a = np.array([10,10,10])
b = np.array([2,3,4])

b

array([2, 3, 4])

In [19]:
# Suma
a + b

array([12, 13, 14])

In [20]:
# Resta
a - b

array([8, 7, 6])

In [21]:
# Multiplicacion
a * 3

array([30, 30, 30])

In [61]:
# Division
a / b
a / 3

array([3.33333333, 3.33333333, 3.33333333])

In [22]:
# Modulo
a % b

array([0, 1, 2])

In [23]:
a % 3

array([1, 1, 1])

In [24]:
muestra = np.arange(20).reshape(5,2,2)

In [25]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [26]:
respuesta_glucosa = muestra > 5 

In [27]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [28]:
muestra[respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
# Mayores a 5 y menores de 14 y que sean pares
muestra = np.arange(20).reshape(5,2,2)
respuesta_glucosa = (muestra > 5) & (muestra < 14) & (muestra % 2 == 0)
muestra[respuesta_glucosa]

array([ 6,  8, 10, 12])

### PRODUCTO PUNTO

In [32]:
import numpy as np

A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [34]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [35]:
A.dot(B) # como la multiplicacion de matrices que aprendí.

array([[ 6,  7],
       [26, 31]])

In [36]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [5]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [37]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
arreglo_doce.sum()

66

In [39]:
arreglo_doce.min()

0

In [40]:
arreglo_doce.max()

11

In [11]:
arreglo_doce[5:].sum()

56

In [41]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [43]:
arreglo_doce.reshape(3,2,2).sum()

66

In [44]:
# Se puede sumar por ejes
arreglo_doce.reshape(3,2,2).sum(axis=0) # Suma cada posición similar de cada matriz

array([[12, 15],
       [18, 21]])

In [45]:
 arreglo_doce.reshape(3,2,2).sum(axis=1) # Sumas por columnas en cada matriz individualmente

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [46]:
arreglo_doce.reshape(3,2,2).sum(axis=2) # Sumas horizontales en cada matriz individualmente

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [4]:
a = [[1,2,3],[5,6,7]]

In [5]:
len(a)

2