In [1]:
import numpy as np

In [3]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
np.zeros(5) # para un arreglo solo se manda un numero 

# Para una matriz se manda una tupla o lista
np.zeros([5,5])
np.zeros((5,5)) 
np.zeros([100,300]) # siempre el último será el parámetros de las columnas y el penúltimo de las filas
np.ones([100,300])

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
# Crea una matriz de igual dimensiones con su diagonal = 1
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### NP.ARANGE

In [32]:
# Establece un inicio y un fin abierto para llenar un array

np.arange(5,20) # [5, 20[

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
np.arange(12,-3)

array([], dtype=int64)

In [33]:
np.arange(5,20,3)  # Del 5 al 20 abierto saltando de 3 en 3

array([ 5,  8, 11, 14, 17])

In [37]:
np.arange(-25,-20,0.7) 

array([-25. , -24.3, -23.6, -22.9, -22.2, -21.5, -20.8, -20.1])

### .RESHAPE

In [47]:
np.arange(20).reshape(5,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [48]:
np.arange(20).reshape(5,2,2).reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
np.arange(20).reshape(5,2,2).shape

(5, 2, 2)

### OPERACIONES

In [55]:
a = np.array([10,10,10])
b = np.array([2,3,4])

b

array([2, 3, 4])

In [57]:
# Suma
a + b

array([12, 13, 14])

In [58]:
# Resta
a - b

array([8, 7, 6])

In [59]:
# Multiplicacion
a * 3

array([30, 30, 30])

In [61]:
# Division
a / b
a / 3

array([3.33333333, 3.33333333, 3.33333333])

In [62]:
# Modulo
a % b

array([0, 1, 2])

In [63]:
a % 3

array([1, 1, 1])

In [132]:
muestra = np.arange(20).reshape(5,2,2)

In [100]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [101]:
respuesta_glucosa = muestra > 5 

In [102]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [104]:
muestra[respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [137]:
# Mayores a 5 y menores de 14 y que sean pares
muestra = np.arange(20).reshape(5,2,2)
respuesta_glucosa = (muestra > 5) & (muestra < 14) & (muestra % 2 == 0)
muestra[respuesta_glucosa]

array([ 6,  8, 10, 12])