In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])
## TRANSFORMACIÓN A RADIANES
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([ 0, 30, 45, 60, 90])

### Funciones trigonométricas

In [6]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [7]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [8]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

### Randomicos

In [61]:
numero_randomico = np.random.randint(3)  # Del 0 al 2
numero_randomico

2

In [62]:
numero_randomico = np.random.randint(-9,2) # Desde el '9' al 1 
numero_randomico

0

In [74]:
arreglo_random = np.random.randint(10,20,3) # el último indica cuántos elementos crear
arreglo_random

array([12, 19, 10])

In [71]:
np.random.rand(3,3,3) # Esto se lo puede recrear con un reshape

array([[[0.87213176, 0.49947074, 0.2173464 ],
        [0.88530649, 0.61808717, 0.28265843],
        [0.80296254, 0.37993433, 0.19447802]],

       [[0.59103444, 0.70364639, 0.88924587],
        [0.9817736 , 0.16589083, 0.17108471],
        [0.38245855, 0.46778683, 0.54518481]],

       [[0.11022491, 0.68003409, 0.37308169],
        [0.45701542, 0.58147922, 0.14583146],
        [0.54060005, 0.14498309, 0.76091579]]])

In [75]:
np.average(arreglo_random)

13.666666666666666

In [76]:
np.mean(arreglo_random )

13.666666666666666

In [77]:
np.median(arreglo_random)

12.0

In [78]:
np.std(arreglo_random)

3.858612300930075

In [79]:
np.var(arreglo_random)

14.888888888888888