In [2]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])
## TRANSFORMACIÓN A RADIANES
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

### Funciones trigonométricas

In [4]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [6]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

### Randomicos

In [7]:
numero_randomico = np.random.randint(3)  # Del 0 al 2
numero_randomico

1

In [10]:
numero_randomico = np.random.randint(-9,2) # Desde el -9 al 1 
numero_randomico

0

In [11]:
arreglo_random = np.random.randint(10,20,3) # el último indica cuántos elementos crear
arreglo_random

array([17, 19, 17])

In [12]:
np.random.rand(3,3,3) # Esto se lo puede recrear con un reshape

array([[[0.71346416, 0.77169527, 0.22465648],
        [0.53799433, 0.67609703, 0.37395566],
        [0.13404831, 0.51647408, 0.81164878]],

       [[0.04575436, 0.42562152, 0.76703419],
        [0.80043315, 0.66252499, 0.24844378],
        [0.86111468, 0.98803407, 0.25066982]],

       [[0.30640718, 0.876118  , 0.84121322],
        [0.95663583, 0.34183087, 0.29755535],
        [0.34944783, 0.12721192, 0.44275955]]])

In [13]:
np.average(arreglo_random)

17.666666666666668

In [14]:
np.mean(arreglo_random )

17.666666666666668

In [15]:
np.median(arreglo_random)

17.0

In [16]:
np.std(arreglo_random) #= np.var **0.5

0.9428090415820634

In [17]:
np.var(arreglo_random) 

0.8888888888888888

In [20]:
0.8888888888888888 ** 0.5

0.9428090415820634