In [1]:
import numpy as np

arreglo = np.arange(11) ** 2
arreglo # desde el uno a 10 todos se elevan al cubo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [2]:
arreglo[0:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [3]:
arreglo[-6:-1]

array([25, 36, 49, 64, 81])

In [4]:
arreglo[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [5]:
arreglo[0:7:2] # Del 0 hasta la posicion 7 de 2 en 2

array([ 0,  4, 16, 36])

In [7]:
arreglo[::-2] # Desde el final al principio de 2 en 2 hacia atrás

array([100,  64,  36,  16,   4,   0])

In [8]:
arreglo[::2] # Desde el principio al final de 2 en 2 

array([  0,   4,  16,  36,  64, 100])